// Generated by gencpp from file trabfinal/altitudeUAV.msg
// DO NOT EDIT!


#ifndef TRABFINAL_MESSAGE_ALTITUDEUAV_H
#define TRABFINAL_MESSAGE_ALTITUDEUAV_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trabfinal
{
template <class ContainerAllocator>
struct altitudeUAV_
{
  typedef altitudeUAV_<ContainerAllocator> Type;

  altitudeUAV_()
    : altitude(0.0)  {
    }
  altitudeUAV_(const ContainerAllocator& _alloc)
    : altitude(0.0)  {
    }



   typedef double _altitude_type;
  _altitude_type altitude;




  typedef boost::shared_ptr< ::trabfinal::altitudeUAV_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trabfinal::altitudeUAV_<ContainerAllocator> const> ConstPtr;

}; // struct altitudeUAV_

typedef ::trabfinal::altitudeUAV_<std::allocator<void> > altitudeUAV;

typedef boost::shared_ptr< ::trabfinal::altitudeUAV > altitudeUAVPtr;
typedef boost::shared_ptr< ::trabfinal::altitudeUAV const> altitudeUAVConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trabfinal::altitudeUAV_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trabfinal::altitudeUAV_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace trabfinal

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'trabfinal': ['/home/jmdbo/TRSA/src/trabfinal/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::trabfinal::altitudeUAV_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trabfinal::altitudeUAV_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trabfinal::altitudeUAV_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trabfinal::altitudeUAV_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trabfinal::altitudeUAV_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trabfinal::altitudeUAV_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trabfinal::altitudeUAV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42af7eb0aaf91dc07d6880f800cabbb3";
  }

  static const char* value(const ::trabfinal::altitudeUAV_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42af7eb0aaf91dc0ULL;
  static const uint64_t static_value2 = 0x7d6880f800cabbb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::trabfinal::altitudeUAV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trabfinal/altitudeUAV";
  }

  static const char* value(const ::trabfinal::altitudeUAV_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trabfinal::altitudeUAV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 altitude\n\
";
  }

  static const char* value(const ::trabfinal::altitudeUAV_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trabfinal::altitudeUAV_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct altitudeUAV_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trabfinal::altitudeUAV_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trabfinal::altitudeUAV_<ContainerAllocator>& v)
  {
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRABFINAL_MESSAGE_ALTITUDEUAV_H
