// Generated by gencpp from file trabfinal/controlUAV.msg
// DO NOT EDIT!


#ifndef TRABFINAL_MESSAGE_CONTROLUAV_H
#define TRABFINAL_MESSAGE_CONTROLUAV_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trabfinal
{
template <class ContainerAllocator>
struct controlUAV_
{
  typedef controlUAV_<ContainerAllocator> Type;

  controlUAV_()
    : altitude(0.0)
    , angle(0.0)  {
    }
  controlUAV_(const ContainerAllocator& _alloc)
    : altitude(0.0)
    , angle(0.0)  {
    }



   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::trabfinal::controlUAV_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trabfinal::controlUAV_<ContainerAllocator> const> ConstPtr;

}; // struct controlUAV_

typedef ::trabfinal::controlUAV_<std::allocator<void> > controlUAV;

typedef boost::shared_ptr< ::trabfinal::controlUAV > controlUAVPtr;
typedef boost::shared_ptr< ::trabfinal::controlUAV const> controlUAVConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trabfinal::controlUAV_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trabfinal::controlUAV_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace trabfinal

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'trabfinal': ['/home/jmdbo/TRSA/src/trabfinal/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::trabfinal::controlUAV_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trabfinal::controlUAV_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trabfinal::controlUAV_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trabfinal::controlUAV_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trabfinal::controlUAV_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trabfinal::controlUAV_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trabfinal::controlUAV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09d83d88ec2b5cbfb495cf94b70c2bfa";
  }

  static const char* value(const ::trabfinal::controlUAV_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09d83d88ec2b5cbfULL;
  static const uint64_t static_value2 = 0xb495cf94b70c2bfaULL;
};

template<class ContainerAllocator>
struct DataType< ::trabfinal::controlUAV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trabfinal/controlUAV";
  }

  static const char* value(const ::trabfinal::controlUAV_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trabfinal::controlUAV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 altitude\n\
float64 angle\n\
";
  }

  static const char* value(const ::trabfinal::controlUAV_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trabfinal::controlUAV_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.altitude);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct controlUAV_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trabfinal::controlUAV_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trabfinal::controlUAV_<ContainerAllocator>& v)
  {
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRABFINAL_MESSAGE_CONTROLUAV_H
