// Generated by gencpp from file trabfinal/imagePosUAV.msg
// DO NOT EDIT!


#ifndef TRABFINAL_MESSAGE_IMAGEPOSUAV_H
#define TRABFINAL_MESSAGE_IMAGEPOSUAV_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trabfinal
{
template <class ContainerAllocator>
struct imagePosUAV_
{
  typedef imagePosUAV_<ContainerAllocator> Type;

  imagePosUAV_()
    : xCenterUAV(0)
    , yCenterUAV(0)
    , xCenterImg(0)
    , yCenterImg(0)  {
    }
  imagePosUAV_(const ContainerAllocator& _alloc)
    : xCenterUAV(0)
    , yCenterUAV(0)
    , xCenterImg(0)
    , yCenterImg(0)  {
    }



   typedef int32_t _xCenterUAV_type;
  _xCenterUAV_type xCenterUAV;

   typedef int32_t _yCenterUAV_type;
  _yCenterUAV_type yCenterUAV;

   typedef int32_t _xCenterImg_type;
  _xCenterImg_type xCenterImg;

   typedef int32_t _yCenterImg_type;
  _yCenterImg_type yCenterImg;




  typedef boost::shared_ptr< ::trabfinal::imagePosUAV_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trabfinal::imagePosUAV_<ContainerAllocator> const> ConstPtr;

}; // struct imagePosUAV_

typedef ::trabfinal::imagePosUAV_<std::allocator<void> > imagePosUAV;

typedef boost::shared_ptr< ::trabfinal::imagePosUAV > imagePosUAVPtr;
typedef boost::shared_ptr< ::trabfinal::imagePosUAV const> imagePosUAVConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trabfinal::imagePosUAV_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trabfinal::imagePosUAV_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace trabfinal

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'trabfinal': ['/home/jmdbo/TRSA/src/trabfinal/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::trabfinal::imagePosUAV_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trabfinal::imagePosUAV_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trabfinal::imagePosUAV_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trabfinal::imagePosUAV_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trabfinal::imagePosUAV_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trabfinal::imagePosUAV_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trabfinal::imagePosUAV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adb802c27b6276c3ccbc3f94082c196a";
  }

  static const char* value(const ::trabfinal::imagePosUAV_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xadb802c27b6276c3ULL;
  static const uint64_t static_value2 = 0xccbc3f94082c196aULL;
};

template<class ContainerAllocator>
struct DataType< ::trabfinal::imagePosUAV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trabfinal/imagePosUAV";
  }

  static const char* value(const ::trabfinal::imagePosUAV_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trabfinal::imagePosUAV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 xCenterUAV\n\
int32 yCenterUAV\n\
int32 xCenterImg\n\
int32 yCenterImg\n\
";
  }

  static const char* value(const ::trabfinal::imagePosUAV_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trabfinal::imagePosUAV_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xCenterUAV);
      stream.next(m.yCenterUAV);
      stream.next(m.xCenterImg);
      stream.next(m.yCenterImg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct imagePosUAV_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trabfinal::imagePosUAV_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trabfinal::imagePosUAV_<ContainerAllocator>& v)
  {
    s << indent << "xCenterUAV: ";
    Printer<int32_t>::stream(s, indent + "  ", v.xCenterUAV);
    s << indent << "yCenterUAV: ";
    Printer<int32_t>::stream(s, indent + "  ", v.yCenterUAV);
    s << indent << "xCenterImg: ";
    Printer<int32_t>::stream(s, indent + "  ", v.xCenterImg);
    s << indent << "yCenterImg: ";
    Printer<int32_t>::stream(s, indent + "  ", v.yCenterImg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRABFINAL_MESSAGE_IMAGEPOSUAV_H
