// Generated by gencpp from file t4_package/ACState.msg
// DO NOT EDIT!


#ifndef T4_PACKAGE_MESSAGE_ACSTATE_H
#define T4_PACKAGE_MESSAGE_ACSTATE_H

#include <ros/service_traits.h>


#include <t4_package/ACStateRequest.h>
#include <t4_package/ACStateResponse.h>


namespace t4_package
{

struct ACState
{

typedef ACStateRequest Request;
typedef ACStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ACState
} // namespace t4_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::t4_package::ACState > {
  static const char* value()
  {
    return "d10b09b6bc031ed40715d35551db280c";
  }

  static const char* value(const ::t4_package::ACState&) { return value(); }
};

template<>
struct DataType< ::t4_package::ACState > {
  static const char* value()
  {
    return "t4_package/ACState";
  }

  static const char* value(const ::t4_package::ACState&) { return value(); }
};


// service_traits::MD5Sum< ::t4_package::ACStateRequest> should match 
// service_traits::MD5Sum< ::t4_package::ACState > 
template<>
struct MD5Sum< ::t4_package::ACStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::t4_package::ACState >::value();
  }
  static const char* value(const ::t4_package::ACStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::t4_package::ACStateRequest> should match 
// service_traits::DataType< ::t4_package::ACState > 
template<>
struct DataType< ::t4_package::ACStateRequest>
{
  static const char* value()
  {
    return DataType< ::t4_package::ACState >::value();
  }
  static const char* value(const ::t4_package::ACStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::t4_package::ACStateResponse> should match 
// service_traits::MD5Sum< ::t4_package::ACState > 
template<>
struct MD5Sum< ::t4_package::ACStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::t4_package::ACState >::value();
  }
  static const char* value(const ::t4_package::ACStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::t4_package::ACStateResponse> should match 
// service_traits::DataType< ::t4_package::ACState > 
template<>
struct DataType< ::t4_package::ACStateResponse>
{
  static const char* value()
  {
    return DataType< ::t4_package::ACState >::value();
  }
  static const char* value(const ::t4_package::ACStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // T4_PACKAGE_MESSAGE_ACSTATE_H
