// Generated by gencpp from file t4_package/ACStateResponse.msg
// DO NOT EDIT!


#ifndef T4_PACKAGE_MESSAGE_ACSTATERESPONSE_H
#define T4_PACKAGE_MESSAGE_ACSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace t4_package
{
template <class ContainerAllocator>
struct ACStateResponse_
{
  typedef ACStateResponse_<ContainerAllocator> Type;

  ACStateResponse_()
    : result(false)  {
    }
  ACStateResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
    }



   typedef uint8_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::t4_package::ACStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::t4_package::ACStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ACStateResponse_

typedef ::t4_package::ACStateResponse_<std::allocator<void> > ACStateResponse;

typedef boost::shared_ptr< ::t4_package::ACStateResponse > ACStateResponsePtr;
typedef boost::shared_ptr< ::t4_package::ACStateResponse const> ACStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::t4_package::ACStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::t4_package::ACStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace t4_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'t4_package': ['/home/jmdbo/trsa_ws/src/t4_package/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::t4_package::ACStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::t4_package::ACStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::t4_package::ACStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::t4_package::ACStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t4_package::ACStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t4_package::ACStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::t4_package::ACStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::t4_package::ACStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::t4_package::ACStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "t4_package/ACStateResponse";
  }

  static const char* value(const ::t4_package::ACStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::t4_package::ACStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
\n\
";
  }

  static const char* value(const ::t4_package::ACStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::t4_package::ACStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ACStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::t4_package::ACStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::t4_package::ACStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // T4_PACKAGE_MESSAGE_ACSTATERESPONSE_H
