// Generated by gencpp from file t4_package/SetTemperature.msg
// DO NOT EDIT!


#ifndef T4_PACKAGE_MESSAGE_SETTEMPERATURE_H
#define T4_PACKAGE_MESSAGE_SETTEMPERATURE_H

#include <ros/service_traits.h>


#include <t4_package/SetTemperatureRequest.h>
#include <t4_package/SetTemperatureResponse.h>


namespace t4_package
{

struct SetTemperature
{

typedef SetTemperatureRequest Request;
typedef SetTemperatureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTemperature
} // namespace t4_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::t4_package::SetTemperature > {
  static const char* value()
  {
    return "739e57d5bb0983212540786c5e3bf89e";
  }

  static const char* value(const ::t4_package::SetTemperature&) { return value(); }
};

template<>
struct DataType< ::t4_package::SetTemperature > {
  static const char* value()
  {
    return "t4_package/SetTemperature";
  }

  static const char* value(const ::t4_package::SetTemperature&) { return value(); }
};


// service_traits::MD5Sum< ::t4_package::SetTemperatureRequest> should match 
// service_traits::MD5Sum< ::t4_package::SetTemperature > 
template<>
struct MD5Sum< ::t4_package::SetTemperatureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::t4_package::SetTemperature >::value();
  }
  static const char* value(const ::t4_package::SetTemperatureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::t4_package::SetTemperatureRequest> should match 
// service_traits::DataType< ::t4_package::SetTemperature > 
template<>
struct DataType< ::t4_package::SetTemperatureRequest>
{
  static const char* value()
  {
    return DataType< ::t4_package::SetTemperature >::value();
  }
  static const char* value(const ::t4_package::SetTemperatureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::t4_package::SetTemperatureResponse> should match 
// service_traits::MD5Sum< ::t4_package::SetTemperature > 
template<>
struct MD5Sum< ::t4_package::SetTemperatureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::t4_package::SetTemperature >::value();
  }
  static const char* value(const ::t4_package::SetTemperatureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::t4_package::SetTemperatureResponse> should match 
// service_traits::DataType< ::t4_package::SetTemperature > 
template<>
struct DataType< ::t4_package::SetTemperatureResponse>
{
  static const char* value()
  {
    return DataType< ::t4_package::SetTemperature >::value();
  }
  static const char* value(const ::t4_package::SetTemperatureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // T4_PACKAGE_MESSAGE_SETTEMPERATURE_H
