(cl:defpackage t4_package-srv
  (:use )
  (:export
   "SETTEMPERATURE"
   "<SETTEMPERATURE-REQUEST>"
   "SETTEMPERATURE-REQUEST"
   "<SETTEMPERATURE-RESPONSE>"
   "SETTEMPERATURE-RESPONSE"
   "DESIREDTEMPERATURE"
   "<DESIREDTEMPERATURE-REQUEST>"
   "DESIREDTEMPERATURE-REQUEST"
   "<DESIREDTEMPERATURE-RESPONSE>"
   "DESIREDTEMPERATURE-RESPONSE"
   "ACSTATE"
   "<ACSTATE-REQUEST>"
   "ACSTATE-REQUEST"
   "<ACSTATE-RESPONSE>"
   "ACSTATE-RESPONSE"
  ))

