// Generated by gencpp from file kelp_ros/ServoControlResponse.msg
// DO NOT EDIT!


#ifndef KELP_ROS_MESSAGE_SERVOCONTROLRESPONSE_H
#define KELP_ROS_MESSAGE_SERVOCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kelp_ros
{
template <class ContainerAllocator>
struct ServoControlResponse_
{
  typedef ServoControlResponse_<ContainerAllocator> Type;

  ServoControlResponse_()
    : result(false)  {
    }
  ServoControlResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
    }



   typedef uint8_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::kelp_ros::ServoControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kelp_ros::ServoControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ServoControlResponse_

typedef ::kelp_ros::ServoControlResponse_<std::allocator<void> > ServoControlResponse;

typedef boost::shared_ptr< ::kelp_ros::ServoControlResponse > ServoControlResponsePtr;
typedef boost::shared_ptr< ::kelp_ros::ServoControlResponse const> ServoControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kelp_ros::ServoControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kelp_ros::ServoControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kelp_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kelp_ros::ServoControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kelp_ros::ServoControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kelp_ros::ServoControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kelp_ros::ServoControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kelp_ros::ServoControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kelp_ros::ServoControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kelp_ros::ServoControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::kelp_ros::ServoControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::kelp_ros::ServoControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kelp_ros/ServoControlResponse";
  }

  static const char* value(const ::kelp_ros::ServoControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kelp_ros::ServoControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
\n\
";
  }

  static const char* value(const ::kelp_ros::ServoControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kelp_ros::ServoControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ServoControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kelp_ros::ServoControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kelp_ros::ServoControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KELP_ROS_MESSAGE_SERVOCONTROLRESPONSE_H
