// Generated by gencpp from file kelp_ros/ServoControl.msg
// DO NOT EDIT!


#ifndef KELP_ROS_MESSAGE_SERVOCONTROL_H
#define KELP_ROS_MESSAGE_SERVOCONTROL_H

#include <ros/service_traits.h>


#include <kelp_ros/ServoControlRequest.h>
#include <kelp_ros/ServoControlResponse.h>


namespace kelp_ros
{

struct ServoControl
{

typedef ServoControlRequest Request;
typedef ServoControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoControl
} // namespace kelp_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kelp_ros::ServoControl > {
  static const char* value()
  {
    return "72af5ec18b305597075cd2db6d215c26";
  }

  static const char* value(const ::kelp_ros::ServoControl&) { return value(); }
};

template<>
struct DataType< ::kelp_ros::ServoControl > {
  static const char* value()
  {
    return "kelp_ros/ServoControl";
  }

  static const char* value(const ::kelp_ros::ServoControl&) { return value(); }
};


// service_traits::MD5Sum< ::kelp_ros::ServoControlRequest> should match 
// service_traits::MD5Sum< ::kelp_ros::ServoControl > 
template<>
struct MD5Sum< ::kelp_ros::ServoControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kelp_ros::ServoControl >::value();
  }
  static const char* value(const ::kelp_ros::ServoControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kelp_ros::ServoControlRequest> should match 
// service_traits::DataType< ::kelp_ros::ServoControl > 
template<>
struct DataType< ::kelp_ros::ServoControlRequest>
{
  static const char* value()
  {
    return DataType< ::kelp_ros::ServoControl >::value();
  }
  static const char* value(const ::kelp_ros::ServoControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kelp_ros::ServoControlResponse> should match 
// service_traits::MD5Sum< ::kelp_ros::ServoControl > 
template<>
struct MD5Sum< ::kelp_ros::ServoControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kelp_ros::ServoControl >::value();
  }
  static const char* value(const ::kelp_ros::ServoControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kelp_ros::ServoControlResponse> should match 
// service_traits::DataType< ::kelp_ros::ServoControl > 
template<>
struct DataType< ::kelp_ros::ServoControlResponse>
{
  static const char* value()
  {
    return DataType< ::kelp_ros::ServoControl >::value();
  }
  static const char* value(const ::kelp_ros::ServoControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KELP_ROS_MESSAGE_SERVOCONTROL_H
