// Generated by gencpp from file t2_package/GameStatus.msg
// DO NOT EDIT!


#ifndef T2_PACKAGE_MESSAGE_GAMESTATUS_H
#define T2_PACKAGE_MESSAGE_GAMESTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace t2_package
{
template <class ContainerAllocator>
struct GameStatus_
{
  typedef GameStatus_<ContainerAllocator> Type;

  GameStatus_()
    : status(0)
    , score()
    , winner(0)  {
      score.assign(0);
  }
  GameStatus_(const ContainerAllocator& _alloc)
    : status(0)
    , score()
    , winner(0)  {
      score.assign(0);
  }



   typedef uint8_t _status_type;
  _status_type status;

   typedef boost::array<uint8_t, 2>  _score_type;
  _score_type score;

   typedef int8_t _winner_type;
  _winner_type winner;


    enum { NEW_BET_SESSION = 0u };
     enum { BET_SESSION_RESULT = 1u };
     enum { GAME_FINISHED = 2u };
 

  typedef boost::shared_ptr< ::t2_package::GameStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::t2_package::GameStatus_<ContainerAllocator> const> ConstPtr;

}; // struct GameStatus_

typedef ::t2_package::GameStatus_<std::allocator<void> > GameStatus;

typedef boost::shared_ptr< ::t2_package::GameStatus > GameStatusPtr;
typedef boost::shared_ptr< ::t2_package::GameStatus const> GameStatusConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::t2_package::GameStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::t2_package::GameStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace t2_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 't2_package': ['/home/jmdbo/TRSA/src/t2_package/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::t2_package::GameStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::t2_package::GameStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::t2_package::GameStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::t2_package::GameStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t2_package::GameStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t2_package::GameStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::t2_package::GameStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f9d99196b01e60e431da38c3d5b9152";
  }

  static const char* value(const ::t2_package::GameStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f9d99196b01e60eULL;
  static const uint64_t static_value2 = 0x431da38c3d5b9152ULL;
};

template<class ContainerAllocator>
struct DataType< ::t2_package::GameStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "t2_package/GameStatus";
  }

  static const char* value(const ::t2_package::GameStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::t2_package::GameStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Constant Definition for game status\n\
uint8 NEW_BET_SESSION = 0\n\
uint8 BET_SESSION_RESULT = 1\n\
uint8 GAME_FINISHED = 2\n\
\n\
uint8 status\n\
uint8[2] score # score[0] = ROS Player; score[1] = Human Player\n\
int8 winner # -1 = Not defined (tie); 0 = ROS Player; 1 = Human Player\n\
";
  }

  static const char* value(const ::t2_package::GameStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::t2_package::GameStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.score);
      stream.next(m.winner);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GameStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::t2_package::GameStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::t2_package::GameStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "score[]" << std::endl;
    for (size_t i = 0; i < v.score.size(); ++i)
    {
      s << indent << "  score[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.score[i]);
    }
    s << indent << "winner: ";
    Printer<int8_t>::stream(s, indent + "  ", v.winner);
  }
};

} // namespace message_operations
} // namespace ros

#endif // T2_PACKAGE_MESSAGE_GAMESTATUS_H
