// Generated by gencpp from file t2_package/Set_Robot_Model.msg
// DO NOT EDIT!


#ifndef T2_PACKAGE_MESSAGE_SET_ROBOT_MODEL_H
#define T2_PACKAGE_MESSAGE_SET_ROBOT_MODEL_H

#include <ros/service_traits.h>


#include <t2_package/Set_Robot_ModelRequest.h>
#include <t2_package/Set_Robot_ModelResponse.h>


namespace t2_package
{

struct Set_Robot_Model
{

typedef Set_Robot_ModelRequest Request;
typedef Set_Robot_ModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Set_Robot_Model
} // namespace t2_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::t2_package::Set_Robot_Model > {
  static const char* value()
  {
    return "51cc362f6d06def3fd71b2dbe3614cc8";
  }

  static const char* value(const ::t2_package::Set_Robot_Model&) { return value(); }
};

template<>
struct DataType< ::t2_package::Set_Robot_Model > {
  static const char* value()
  {
    return "t2_package/Set_Robot_Model";
  }

  static const char* value(const ::t2_package::Set_Robot_Model&) { return value(); }
};


// service_traits::MD5Sum< ::t2_package::Set_Robot_ModelRequest> should match 
// service_traits::MD5Sum< ::t2_package::Set_Robot_Model > 
template<>
struct MD5Sum< ::t2_package::Set_Robot_ModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::t2_package::Set_Robot_Model >::value();
  }
  static const char* value(const ::t2_package::Set_Robot_ModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::t2_package::Set_Robot_ModelRequest> should match 
// service_traits::DataType< ::t2_package::Set_Robot_Model > 
template<>
struct DataType< ::t2_package::Set_Robot_ModelRequest>
{
  static const char* value()
  {
    return DataType< ::t2_package::Set_Robot_Model >::value();
  }
  static const char* value(const ::t2_package::Set_Robot_ModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::t2_package::Set_Robot_ModelResponse> should match 
// service_traits::MD5Sum< ::t2_package::Set_Robot_Model > 
template<>
struct MD5Sum< ::t2_package::Set_Robot_ModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::t2_package::Set_Robot_Model >::value();
  }
  static const char* value(const ::t2_package::Set_Robot_ModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::t2_package::Set_Robot_ModelResponse> should match 
// service_traits::DataType< ::t2_package::Set_Robot_Model > 
template<>
struct DataType< ::t2_package::Set_Robot_ModelResponse>
{
  static const char* value()
  {
    return DataType< ::t2_package::Set_Robot_Model >::value();
  }
  static const char* value(const ::t2_package::Set_Robot_ModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // T2_PACKAGE_MESSAGE_SET_ROBOT_MODEL_H
