// Generated by gencpp from file t2_package/Set_Robot_ModelResponse.msg
// DO NOT EDIT!


#ifndef T2_PACKAGE_MESSAGE_SET_ROBOT_MODELRESPONSE_H
#define T2_PACKAGE_MESSAGE_SET_ROBOT_MODELRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <t2_package/robot_id.h>

namespace t2_package
{
template <class ContainerAllocator>
struct Set_Robot_ModelResponse_
{
  typedef Set_Robot_ModelResponse_<ContainerAllocator> Type;

  Set_Robot_ModelResponse_()
    : robotID()  {
    }
  Set_Robot_ModelResponse_(const ContainerAllocator& _alloc)
    : robotID(_alloc)  {
    }



   typedef  ::t2_package::robot_id_<ContainerAllocator>  _robotID_type;
  _robotID_type robotID;




  typedef boost::shared_ptr< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Set_Robot_ModelResponse_

typedef ::t2_package::Set_Robot_ModelResponse_<std::allocator<void> > Set_Robot_ModelResponse;

typedef boost::shared_ptr< ::t2_package::Set_Robot_ModelResponse > Set_Robot_ModelResponsePtr;
typedef boost::shared_ptr< ::t2_package::Set_Robot_ModelResponse const> Set_Robot_ModelResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace t2_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 't2_package': ['/home/jmdbo/TRSA/src/t2_package/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c6e7b025d512f0c651bae0b3614dcd7";
  }

  static const char* value(const ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c6e7b025d512f0cULL;
  static const uint64_t static_value2 = 0x651bae0b3614dcd7ULL;
};

template<class ContainerAllocator>
struct DataType< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "t2_package/Set_Robot_ModelResponse";
  }

  static const char* value(const ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "t2_package/robot_id robotID\n\
\n\
\n\
================================================================================\n\
MSG: t2_package/robot_id\n\
Header header\n\
int8 id\n\
string model\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robotID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Set_Robot_ModelResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::t2_package::Set_Robot_ModelResponse_<ContainerAllocator>& v)
  {
    s << indent << "robotID: ";
    s << std::endl;
    Printer< ::t2_package::robot_id_<ContainerAllocator> >::stream(s, indent + "  ", v.robotID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // T2_PACKAGE_MESSAGE_SET_ROBOT_MODELRESPONSE_H
