// Generated by gencpp from file t2_package/SetBet.msg
// DO NOT EDIT!


#ifndef T2_PACKAGE_MESSAGE_SETBET_H
#define T2_PACKAGE_MESSAGE_SETBET_H

#include <ros/service_traits.h>


#include <t2_package/SetBetRequest.h>
#include <t2_package/SetBetResponse.h>


namespace t2_package
{

struct SetBet
{

typedef SetBetRequest Request;
typedef SetBetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBet
} // namespace t2_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::t2_package::SetBet > {
  static const char* value()
  {
    return "5d93a0c5d016c9a6bcb0a3b38a993147";
  }

  static const char* value(const ::t2_package::SetBet&) { return value(); }
};

template<>
struct DataType< ::t2_package::SetBet > {
  static const char* value()
  {
    return "t2_package/SetBet";
  }

  static const char* value(const ::t2_package::SetBet&) { return value(); }
};


// service_traits::MD5Sum< ::t2_package::SetBetRequest> should match 
// service_traits::MD5Sum< ::t2_package::SetBet > 
template<>
struct MD5Sum< ::t2_package::SetBetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::t2_package::SetBet >::value();
  }
  static const char* value(const ::t2_package::SetBetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::t2_package::SetBetRequest> should match 
// service_traits::DataType< ::t2_package::SetBet > 
template<>
struct DataType< ::t2_package::SetBetRequest>
{
  static const char* value()
  {
    return DataType< ::t2_package::SetBet >::value();
  }
  static const char* value(const ::t2_package::SetBetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::t2_package::SetBetResponse> should match 
// service_traits::MD5Sum< ::t2_package::SetBet > 
template<>
struct MD5Sum< ::t2_package::SetBetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::t2_package::SetBet >::value();
  }
  static const char* value(const ::t2_package::SetBetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::t2_package::SetBetResponse> should match 
// service_traits::DataType< ::t2_package::SetBet > 
template<>
struct DataType< ::t2_package::SetBetResponse>
{
  static const char* value()
  {
    return DataType< ::t2_package::SetBet >::value();
  }
  static const char* value(const ::t2_package::SetBetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // T2_PACKAGE_MESSAGE_SETBET_H
