(cl:defpackage t2_package-srv
  (:use )
  (:export
   "SET_ROBOT_MODEL"
   "<SET_ROBOT_MODEL-REQUEST>"
   "SET_ROBOT_MODEL-REQUEST"
   "<SET_ROBOT_MODEL-RESPONSE>"
   "SET_ROBOT_MODEL-RESPONSE"
   "SETBET"
   "<SETBET-REQUEST>"
   "SETBET-REQUEST"
   "<SETBET-RESPONSE>"
   "SETBET-RESPONSE"
   "ACTIVATE"
   "<ACTIVATE-REQUEST>"
   "ACTIVATE-REQUEST"
   "<ACTIVATE-RESPONSE>"
   "ACTIVATE-RESPONSE"
  ))

